on:
  - pull_request
  - push

name: PHPStan

jobs:
  run:
    name: Analyze code with PHPStan

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '8.4' ]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install dependencies with composer
        run: composer install

      - name: Run tests
        run: make phpstan
